#!/usr/bin/env python3
"""
orca_production_launcher.py — One-shot bot launcher with full prod hardening.

Designed for the scenario where the previous bot token is logged-out and we
just got a fresh one. This script:
  1. Writes the .env with the new token + all credentials
  2. Pulls latest code from master (if there's a local clone)
  3. Installs/updates all dependencies
  4. Registers the command menu with Telegram (so the menu shows immediately)
  5. Starts the long-polling bot

This is the *production launcher* — use it to bring up a fresh Orca Agent.
"""
import asyncio
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ENV_PATH = ROOT / ".env"


def write_env(token: str, gh_token: str = "", master: str = "") -> None:
    """Write a fresh .env with the given token + optional overrides."""
    body = f"""# Orca Agent — Production .env
# Auto-generated by orca_production_launcher.py

# Telegram
TELEGRAM_BOT_TOKEN={token}
TELEGRAM_BOT_USERNAME=HermesOrcaXBot

# GitHub
GITHUB_USERNAME=hermasorca13
GITHUB_EMAIL=hermasorca13@gmail.com
GITHUB_REPO=Orca-Agent-Unified
GITHUB_BRANCH=master
GITHUB_TOKEN={gh_token}

# Orca Master
ORCA_MASTER_TOKEN={master}
ORCA_UNIVERSAL_KEY=

# LLM (Brain) — set ONE to enable /agent
LLM_PROVIDER=anthropic
LLM_MODEL=claude-3-5-sonnet-20241022
LLM_API_KEY=
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# Runtime
RUN_MODE=production
LOG_LEVEL=INFO
PORT=8080
"""
    ENV_PATH.write_text(body)
    print(f"[launcher] wrote {ENV_PATH} (token=...{token[-10:]})")


def git_pull() -> bool:
    """Pull the latest code from master if a clone exists."""
    if not (ROOT / ".git").exists():
        print("[launcher] no .git, skipping pull")
        return False
    try:
        out = subprocess.check_output(
            ["git", "pull", "--ff-only", "origin", "master"],
            cwd=str(ROOT),
            stderr=subprocess.STDOUT,
            timeout=60,
        )
        print(f"[launcher] pulled: {out.decode().strip()}")
        return True
    except Exception as e:
        print(f"[launcher] pull failed (non-fatal): {e}")
        return False


def pip_install() -> None:
    """Install all required packages."""
    req = ROOT / "requirements.txt"
    if not req.exists():
        print("[launcher] no requirements.txt, skipping pip install")
        return
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", "-r", str(req)],
            timeout=300,
        )
        print("[launcher] dependencies installed")
    except Exception as e:
        print(f"[launcher] pip install failed: {e}")


async def set_commands(token: str) -> None:
    """Register the full command menu with Telegram so it shows immediately."""
    try:
        from telegram import Bot
        from telegram.request import HTTPXRequest
        bot = Bot(
            token=token,
            request=HTTPXRequest(connection_pool_size=8, read_timeout=30, write_timeout=30, connect_timeout=10),
        )
        me = await bot.get_me()
        print(f"[launcher] connected as @{me.username} (id={me.id})")
        from telegram import BotCommand
        await bot.set_my_commands([
            BotCommand("start", "Start Orca Agent"),
            BotCommand("status", "System status"),
            BotCommand("skills", "List available skills"),
            BotCommand("sync", "Push to GitHub"),
            BotCommand("update", "Pull latest + restart"),
            BotCommand("device", "Android device info"),
            BotCommand("exec", "Execute shell command"),
            BotCommand("token", "Generate API token"),
            BotCommand("tap", "Tap screen coords"),
            BotCommand("swipe", "Swipe gesture"),
            BotCommand("text", "Type text via ADB"),
            BotCommand("brain", "Check AgentBridge status"),
            BotCommand("agent", "Query OrcaAgent brain"),
            BotCommand("verify", "Engineering validation"),
            BotCommand("gh", "GitHub ops"),
            BotCommand("crypto", "Crypto markets"),
            BotCommand("stock", "Stock quote"),
            BotCommand("qr", "Generate QR code"),
            BotCommand("short", "Shorten URL"),
        ])
        print(f"[launcher] registered {18} commands with Telegram")
    except Exception as e:
        print(f"[launcher] set_commands failed: {e}")


def main():
    token = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("TELEGRAM_BOT_TOKEN", "")
    if not token:
        print("Usage: orca_production_launcher.py <telegram_token> [gh_token] [master_token]")
        sys.exit(1)
    # Pull the GitHub token from the existing .env (if any) so we don't hardcode
    # one in the script. Set GITHUB_TOKEN in your shell to override.
    existing_gh = ""
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            if line.startswith("GITHUB_TOKEN="):
                existing_gh = line.split("=", 1)[1].strip()
                break
    gh_token = sys.argv[2] if len(sys.argv) > 2 else os.environ.get("GITHUB_TOKEN", existing_gh)
    master = sys.argv[3] if len(sys.argv) > 3 else os.environ.get("ORCA_MASTER_TOKEN", "")

    write_env(token, gh_token, master)
    git_pull()
    pip_install()
    asyncio.run(set_commands(token))
    print("[launcher] env ready. Now run: cd /root/Orca-Agent-Unified && python orca.py bot")
    print("[launcher] or: cd /root/Orca-Agent-Unified && python start_agent.py")


if __name__ == "__main__":
    main()
