<#
setup/cache_setup.ps1 - Redirect model and package caches to D: drive.

Why: the laptop has a small (168 GB) SSD for the OS and a large
(700 GB) HDD for data. We want to keep the SSD lean for OS speed.
This script moves every cache directory that grows large over time
to the HDD under D:\ORCA AGENT\cache\.

What it does (idempotent - safe to re-run):

  1. Creates D:\ORCA AGENT\cache\ subdirectories
  2. Sets pip's global cache-dir to D:\ORCA AGENT\cache\pip
  3. Creates env-var files for HF_HOME, TORCH_HOME, NLTK_DATA,
     PYTHONPYCACHEPREFIX, etc. -> loaded by run_bot.ps1
  4. Optionally creates NTFS directory junctions so the
     default cache locations transparently point to D:

Usage (from setup.ps1, automatic):
    powershell -NoProfile -ExecutionPolicy Bypass -File setup\cache_setup.ps1 -CacheRoot "D:\ORCA AGENT\cache"

Or manually:
    .\setup\cache_setup.ps1 -CacheRoot "D:\ORCA AGENT\cache"
    .\setup\cache_setup.ps1 -CacheRoot "D:\ORCA AGENT\cache" -UseJunctions  # also redirect %LocalAppData%\pip\Cache
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$CacheRoot,
    [switch]$UseJunctions = $false
)

$ErrorActionPreference = 'Stop'

function Write-Step { param($msg) Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Ok   { param($msg) Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "  [!] $msg" -ForegroundColor Yellow }

Write-Step "Cache redirection to $CacheRoot"

# 1. Create the cache subdirectories
$dirs = @(
    "pip",                  # pip download cache
    "huggingface",          # HF_HOME: transformers, datasets, hub
    "torch",                # TORCH_HOME: hub, checkpoints
    "nltk_data",            # NLTK_DATA: corpora
    "yolo",                 # YOLO_CONFIG_DIR: model weights
    "triton",               # TRITON_CACHE_DIR: compiled kernels
    "matplotlib",           # MPLCONFIGDIR: font cache
    "pytest",               # pytest cache
    "logs"                  # bot logs
)
foreach ($d in $dirs) {
    $path = Join-Path $CacheRoot $d
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
    Write-Ok "Created $path"
}

# 2. Configure pip cache
Write-Step "Configuring pip"
$pipCacheDir = Join-Path $CacheRoot "pip"
& pip config set global.cache-dir $pipCacheDir 2>&1 | Out-Null
$verify = & pip config get global.cache-dir 2>&1
if ($verify -like "*$CacheRoot*") {
    Write-Ok "pip cache-dir: $verify"
} else {
    Write-Warn "pip config set may have failed; manual check: pip config get global.cache-dir"
}

# 3. Write env-var file that run_bot.ps1 will source
Write-Step "Writing env vars for run_bot.ps1"
$envFile = Join-Path $CacheRoot "cache_env.ps1"
$envContent = @"
# Auto-generated by setup\cache_setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Source this file from run_bot.ps1 to redirect all caches to D: drive.

`$env:PIP_CACHE_DIR = "$pipCacheDir"
`$env:HF_HOME = "$(Join-Path $CacheRoot 'huggingface')"
`$env:HUGGINGFACE_HUB_CACHE = "$(Join-Path $CacheRoot 'huggingface' + '\hub')"
`$env:TRANSFORMERS_CACHE = "$(Join-Path $CacheRoot 'huggingface' + '\hub')"
`$env:TORCH_HOME = "$(Join-Path $CacheRoot 'torch')"
`$env:NLTK_DATA = "$(Join-Path $CacheRoot 'nltk_data')"
`$env:YOLO_CONFIG_DIR = "$(Join-Path $CacheRoot 'yolo')"
`$env:TRITON_CACHE_DIR = "$(Join-Path $CacheRoot 'triton')"
`$env:MPLCONFIGDIR = "$(Join-Path $CacheRoot 'matplotlib')"
`$env:PYTHONPYCACHEPREFIX = "$(Join-Path $CacheRoot 'pycache')"
`$env:PIP_DISABLE_PIP_VERSION_CHECK = "1"
`$env:PYTHONDONTWRITEBYTECODE = "0"  # keep .pyc (faster startup) but in D:
"@
$envContent | Set-Content $envFile -Encoding UTF8
Write-Ok "Wrote $envFile (source this from run_bot.ps1)"

# 4. Optional: create NTFS junctions so the default locations
#    (e.g. %LocalAppData%\pip\Cache) transparently point to D:
if ($UseJunctions) {
    Write-Step "Creating NTFS junctions (UseJunctions=$UseJunctions)"
    $junctions = @(
        @{ Source = (Join-Path $env:LOCALAPPDATA "pip\Cache");       Target = $pipCacheDir },
        @{ Source = (Join-Path $env:USERPROFILE   ".cache\huggingface"); Target = (Join-Path $CacheRoot "huggingface") },
        @{ Source = (Join-Path $env:USERPROFILE   ".cache\torch");       Target = (Join-Path $CacheRoot "torch") }
    )
    foreach ($j in $junctions) {
        $src = $j.Source
        $tgt = $j.Target
        if (Test-Path $src) {
            if ((Get-Item $src).Attributes -band [IO.FileAttributes]::ReparsePoint) {
                Write-Ok "Junction already exists: $src"
            } else {
                Write-Warn "$src exists but is not a junction; leaving alone"
            }
        } else {
            $parent = Split-Path $src -Parent
            if (-not (Test-Path $parent)) {
                New-Item -ItemType Directory -Path $parent -Force | Out-Null
            }
            & cmd /c mklink /J "$src" "$tgt" 2>&1 | Out-Null
            if (Test-Path $src) {
                Write-Ok "Created junction: $src -> $tgt"
            } else {
                Write-Warn "Failed to create junction: $src"
            }
        }
    }
} else {
    Write-Host "  (UseJunctions not set - skipping junction creation)"
    Write-Host "  Run with -UseJunctions to also redirect %LocalAppData%\pip\Cache"
}

Write-Host ""
Write-Host "Cache redirection done." -ForegroundColor Green
Write-Host "  Cache root: $CacheRoot"
Write-Host "  Env file:   $envFile"
Write-Host "  run_bot.ps1 will auto-source this file on startup."
